/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Softcap": "软上限",
    "They DON'T reset unless said so.": "除非这样说，否则他们不会重置。",
    "You can buy max elections": "您可以购买最大选举",
    "You can buy max members": "您可以购买最大人员",
    "You can't gain prestige points": "你无法获得声望点数",
    "Leave!": "离开！",
    "Anti-Prestige": "反声望",
    "Anti-Challenge points": "反挑战点",
    "Endgame: 1e50 Rigged Poll": "残局：1e50 操纵民意调查",
    "Member effect is disabled": "人员效果被禁用",
    "Get 1e58 points.": "获得 1e58 点数。",
    "For every challenge you complete, you'll gain an anti-challenge point.": "对于您完成的每个挑战，您将获得一个反挑战点。",
    "\tGoal:": "\t目标:",
    "\tReward": "\t奖励",
    "A completely useless clickable.": "一个完全没用的可点击。",
    "ant warmer": "蚂蚁保温器",
    "Boost your point gain based on cbrt(prestige point+1).": "根据 cbrt（声望点+1）提高您的点数增益。",
    "Boost your point gain based on your prestige point.": "根据您的声望点提高您的点数增益。",
    "Boost your prestige point gain based on your point.": "根据您的点数提高您的声望点数。",
    "Buyable points": "可购买点数",
    "Double your point gain.": "双倍您的点数增益。",
    "easy": "简单",
    "enter easy mode": "进入简单模式",
    "For every buyable you buy, you'll gain an buyable point.": "对于您购买的每个可购买，您将获得一个可购买点数。",
    "Prestige points": "声望点",
    "Unlock Anti-challenge.": "解锁反挑战。",
    "Unlock other buyable.": "解锁其它可购买。",
    "Unlock next upgrade.": "解锁下一个升级。",
    "upvoid": "虚无",
    "An upgrade. Buy this.": "一个升级。 购买这个。",
    "Devide your point gain by 2.": "将您的点数收益除以 2。",
    "InFiIipity♾": "无穷无尽♾",
    "inflation": "通货膨胀",
    "Multiplies point gain by 1.1 .": "将点数增益乘以 1.1 。",
    "Not an upgrade, don't buy this.": "不是升级，不要买这个。",
    "Click here to waste points.": "点击这里浪费点数。",
    "Add 0.5 to buyable 2 base for 10 seconds,": "将 0.5 添加到可购买 2 基数上，持续 10 秒，",
    "After buying, it will be /0.2 instead of /2.": "购买后，它将是 /0.2 而不是 /2。",
    "Divides the fourth upvoid effect by 10.": "将第四个向上虚空效果除以 10。",
    "Doubles point gain for 10 seconds,": "10 秒内获得双倍点数，",
    "Increases the exponent of the 3^3=7 upgrade based on rigged polls.": "基于被操纵的民意调查增加 3^3=7 升级的指数。",
    "Keep prestige upgrades on reset": "重置时保持声望升级",
    "Make the cilckable in prestige layer \"Do Something\".": "使声望层中的可点击“做点什么”。",
    "Meo": "梅奥",
    "Multiplies point gain by (points^(1-1/ln(points+1))).": "将点数增益乘以 (点数^(1-1/ln(点数+1)))。",
    "multiply prestige point gain by ln((log2(ln(points+1)+1)+1)^(log10(prestige points+1)^0.9+1)+1)+1": "将声望点增益乘以ln((log2(ln(点数+1)+1)+1)^(log10(声望点+1)^0.9+1)+1)+1",
    "Point gain *(average temperature of earth in degrees celsius": "点增益*（地球的平均温度，以摄氏度为单位",
    "point x3^3 (7).": "点数 x3^3 (7).",
    "Raise point gain by 1.1.": "将点数增益提高 1.1。",
    "Rigged Polls": "被操纵的民意调查",
    "Square prestige gain": "平方声望增益",
    "Unlock an upgrade in prestige layer.": "解锁声望层的升级。",
    "Boost point gain by x2.": "将点数增益提高 x2。",
    "Next: MAXED": "下一个: 最大",
    "Adds 5 to base point gain, and then multiplies point gain by 5.": "将基础点数增益加 5，然后将点数增益乘以 5。",
    "Auto gain 10% of prestige point on prestige per second.": "每秒自动获得声望点 10% 的声望点。",
    "Fumo": "Fumo",
    "Boost point gain by 2x.": "将点数增益提高 2 倍。",
    "Challenge points": "挑战点",
    "Click me to change color to purple.": "点我将颜色更改为紫色。",
    "effect goes log10": "效果是log10",
    "Election Polls": "选举民意调查",
    "Elections have a useful effect (very useful trust me": "选举产生了有用的效果（非常有用相信我",
    "elunds": "埃伦兹",
    "Except first one.": "除了第一个。",
    "For every challenge you complete, you'll gain an challenge point.": "对于您完成的每个挑战，您将获得一个挑战点。",
    "gain 4.9 fumos": "获得 4.9 fumo",
    "Nope.": "不。",
    "nothing": "没有",
    "point gain is multiplied by community": "点数增益乘以社区",
    "point gain log2, but raised to the log2(time since reset+2": "点增益 log2，但提高到 log2(重置+2 后的时间",
    "Start at 0x.": "从 0x 开始。",
    "This is an free challenge.": "这是一个免费的挑战。",
    "This layer have nothing now as noone suggest and i don't know how to make an upgrade tree ;-;": "这一层现在没有任何人建议，我不知道如何制作升级树;-;",
    "This layer resets all row 1 and 2 layers except anti challenges": "该层重置除反挑战之外的所有第 1 行和第 2 行",
    "Unlock the third rigged poll upgrade.": "解锁第三次操纵投票升级。",
    "watglan": "瓦特格兰",
    "Your buyable effect is x2.": "您的可购买效果为 x2。",
    "Your buyable effect is square rooted.": "您的可购买效应是平方根的。",
    "effect -> ln(effect+1": "效果 -> ln(效果+1",
    "election polls multiply prestige gain": "选举民意测验成倍增加声望",
    "elections": "选举",
    "Gain the square root of rigged polls on reset per second": "每秒重置时获得操纵民意调查的平方根",
    "increase the softcap exponent of rigged poll upgrade 14 based on members": "根据成员增加操纵投票升级 14 的软上限指数",
    "Keep rigged poll milestones on reset": "在重置时保持操纵的投票里程碑",
    "Keep rigged poll upgrades on reset": "在重置时保持操纵民意调查升级",
    "Members": "成员",
    "Multiplies point gain by light mode.": "通过光模式乘以点增益。",
    "Multiply point gain by log(points+1": "将点数增益乘以 log(点数+1",
    "multiplying point gain by 1.01": "乘以点数增益 1.01",
    "Summon a fortified camo regrow red and a regular blue bloon.": "召唤一个强化的迷彩再生红色和一个普通的蓝色气球。",
    "upgrades": "升级",
    "votes": "选票",
    "A: Reset for addition": "A: 重置加成",
    "C: Reset for Members": "C：重置成员",
    "Clicked 200.00 times.": "点击了 200.00 次。",
    "E: Reset for Elections": "E: 重置选举",
    "P: Reset for prestige points": "P：重置声望点",
    "R: Reset for Rigged Polls": "R：重置操纵民意调查",
    "Unlocked 1.00 more buyable.": "解锁 1.00 可购买。",
    "V: Reset for votes": "V：重置选票",
    "bloons": "气球",
    "Addition": "加成",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Fawwaz Arkan": "法瓦兹·阿坎",
    "Elund": "埃隆德",
    "And a +1 output as Fawwaz Arkan suggest": "和 法瓦兹·阿坎 建议的 +1 输出",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "effect ^": "效果 ^",
    "Start at +": "开始于 +",
    "Actual Formula:": "实际公式：",
    "point gain ^": "点数增益 ^",
    "Current light mode: ": "当前灯光模式：",
    "Currently: ": "当前: ",
    "each prestige upgrade upgrades the first prestige upgrade by ": "每个声望升级升级第一个声望升级",
    "prestige gain ": "声望增益 ",
    "Raise the softcap power of inflation to the ": "将通货膨胀的软上限提高到",
    "rigged poll upgrade ": "操纵民意调查升级",
    "Which is boost yout Rigged Polls gain by ": "这会提高你的 操纵民意调查 收益",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) Prestige points per second$/, '你每秒获得 $1 点声望点数'],
    [/^Reach (.+) Rigged Polls to unlock \(You have (.+) Rigged Polls$/, '达到 $1 被操纵的民意调查去解锁（你有 $2 被操纵的民意调查'],
    [/^Reach (.+) Prestige points to unlock \(You have (.+) Prestige points$/, '达到 $1 声望点去解锁（你有 $2 声望点'],
    [/^Reach (.+) prestige points to unlock \(You have (.+) prestige points$/, '达到 $1 声望点去解锁（你有 $2 声望点'],
    [/^Your point gain is (.+) in this challenge.$/, '在此挑战中，您的积分增益为 $1。'],
    [/^Currently: Unlocked (.+) more buyable.$/, '目前：解锁了 $1 可购买。'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You are gaining (.+) Rigged Polls per second$/, '您每秒获得 $1 操纵民意调查'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) Rigged Polls$/, '你有 $1 操纵民意调查'],
    [/^Next at (.+) Prestige points$/, '下一个在 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Get (.+) points.$/, '获得 $1 点数'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分 $2秒'],
	[/^([\d\.]+)\% to endgame$/, '$1\% 到游戏终点'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) Anti-Challenge points$/, '$1 反挑战点'],
    [/^([\d\.]+) Buyable point$/, '$1 可购买点'],
    [/^([\d\.]+) Buyable points$/, '$1 可购买点'],
    [/^([\d\.]+) Prestige points$/, '$1 声望点'],
    [/^([\d\.]+)e([\d\.,]+) Prestige points$/, '$1e$2 声望点'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) Rigged Polls$/, '$1e$2 操纵民意调查'],
    [/^([\d\.]+)e([\d\.,]+) Addition$/, '$1e$2 加成'],
    [/^([\d\.]+)e([\d\.,]+) votes$/, '$1e$2 选票'],
    [/^([\d\.,]+) Challenge points$/, '$1 挑战点'],
    [/^([\d\.,]+) Election Polls$/, '$1 选举民意调查'],
    [/^([\d\.,]+) Fumo$/, '$1 Fumo'],
    [/^([\d\.,]+) election polls$/, '$1 选举民意调查'],
    [/^([\d\.,]+) Prestige points$/, '$1 声望点'],
    [/^([\d\.,]+) rigged polls$/, '$1 被操纵的民意调查'],
    [/^([\d\.,]+) Rigged Polls$/, '$1 被操纵的民意调查'],
    [/^([\d\.,]+) members$/, '$1 成员'],
    [/^([\d\.,]+) Members$/, '$1 成员'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Next: (.+) prestige points.$/, '下一个：$1 声望点数'],
    [/^Next: (.+) points.$/, '下一个：$1 点数'],
    [/^Currently: (.+)s.$/, '当前：$1秒。'],
    [/^Currently: (.+)x.$/, '当前：$1x。'],
    [/^Next: (.+) Rigged Polls.$/, '下一个：$1 被操纵的民意调查。'],
    [/^Cost: (.+) Fumo$/, '成本：$1 Fumo'],
    [/^Cost: (.+) Members$/, '成本：$1 成员'],
    [/^Cost: (.+) Addition$/, '成本：$1 加成'],
    [/^Cost: (.+) Election Polls$/, '成本：$1 选举民意调查'],
    [/^Cost: (.+) Prestige points$/, '成本：$1 声望点数'],
    [/^Cost: (.+) Rigged Polls$/, '成本：$1 被操纵的民意调查'],
    [/^Cost: (.+) Rigged Polls.$/, '成本：$1 被操纵的民意调查。'],
    [/^Cost:(.+) Rigged Polls.$/, '成本：$1 被操纵的民意调查。'],
    [/^Cost: (.+) Buyable points$/, '成本：$1 可购买点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) Rigged Polls$/, '成本：$1 \/ $2 被操纵的民意调查'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);